### ISSUE TITLE
QCamera2 build error

### ISSUE THREAD

**Issue by yurikoles** [redmidevs/android_vendor_xiaomi_rolex#1]
I'm facing an issue during build:
```
device/xiaomi/rolex/camera/QCamera2: MODULE.TARGET.SHARED_LIBRARIES.camera.msm8937_32 already defined by device/xiaomi/msm8917-common/camera/QCamera2
```

**Comment by 33bca** [comment]
Remove msm8917-common device and vendor sources ;D

**Comment by yurikoles** [comment]
@33bca please be more specific.

**Comment by yurikoles** [comment]
I use local manifest from your repo. Could you please update it?

**Comment by 33bca** [comment]
I'm sorry, I forgot to update them, feel free to use the new one.
or simply remove devices/xiaomi/msm8917-common and vendor/xiaomi/msm8917-common.
